### ISSUE TITLE
Http response 404

### ISSUE THREAD

**Issue by jjproe** [NeedleInAJayStack/needleinajaystack-haystack-datasource#32]
Hello,

I'm trying to start a Grafana - Skypark V3 connection. But when creating the data source and saving/testing, http status 404 comes up.
In the past I had implemented a Python connection according to the description on the alienfactory site. There I had to use the uri+/api for the HELLO request. At /about I get this 404 error..
I've seen various examples that use this - /about uri. 
Is there an error in the Skyspark installation?
Thanks in advance

**Comment by NeedleInAJayStack** [comment]
Hi!

If you haven't seen it yet, definitely follow the directions in this file: https://github.com/NeedleInAJayStack/needleinajaystack-haystack-datasource/blob/main/src/README.md

Specifically with SkySpark, your url must include the project name, and not include the '/about'. So if your SkySpark was at 'http://skyspark.mycompany.com' and your project was named 'myProj' then the url would be: 'http://skyspark.mycompany.com/api/myProj/'

Let me know if that doesn't work.

**Comment by jjproe** [comment]
Hello,
it works, that's it !
I had originally entered the correct URL, probably a typo.

Thank you very much !

**Comment by NeedleInAJayStack** [comment]
Great, I'm glad that fixed it!
